### ISSUE TITLE
1.1/statuses/mentions_timeline returning code=200 with empty results

### ISSUE THREAD

**Issue by oosswwaalldd** [themattharris/tmhOAuth#100]
Hi Matt, 

I am experiencing some problems trying to get mentions timeline of an authenticated user using the new 1.1 API 1.1/statuses/mentions_timeline

```
$tmhOAuth->request('GET', $tmhOAuth->url('1.1/statuses/mentions_timeline'), array( 'count' => 200));    
```

I have a validation to merge the response array if the code is 200, but something strange is happening, there is in fact a code 200 (success) but there are empty JSON arrays as result.

I have to run the call several times to get the mentions, or even lower the count parameter to 150 and 100, but the problem persists.

Is there any problem with the lib or there is a bug in the new implementation of the 1.1 API version?

Thanks for taking the time to make this lib.

**Comment by themattharris** [comment]
this sounds more like an issue with the Twitter API not returning data rather than the lib.
the library makes the request to the API and decodes the JSON response. it also doesn't attempt to filter the data returned by the API - so if the responses is an empty array, that's what the twitter api returned.

if you want to check the exact response from twitter you can inspect `$tmhOAuth->response['raw']` (which is the concatenation of the response header and body).

if you continue to have issues with that api method i recommend letting the @twitterapi team know.
