### ISSUE TITLE
Adding extra parameters to API calls

### ISSUE THREAD

**Issue by nadiamoe** [themattharris/tmhOAuth#12]
Hi there!
I don't really know if this is an issue of your library or a a Twitter API fault, but i can't get the querys to work if I add extra parameters to them.
Example:
    $tmhOAuth->request('GET', $tmhOAuth->url("1/statuses/mentions"));
    $mentions = json_decode($tmhOAuth->response['response']);
This works fine.
    $tmhOAuth->request('GET', $tmhOAuth->url("1/statuses/mentions?since_id=$lasttweet"));
    $timeline = json_decode($tmhOAuth->response['response']);
Where $lasttweet is a positive integer, smaller than the last reply's id. $timeline is empty.

Regards, & thanks in advance ^.^

**Comment by themattharris** [comment]
Hey,

When specifying arguments you should pass them as an array rather than part of the request. My library handles the signing and concatenation for you.

For example:

$tmhOAuth->request('GET', $tmhOAuth->url("1/statuses/mentions"), array(
    'since_id' => $lasttweet
));

That should work for you - let me know how it goes.

**Comment by nadiamoe** [comment]
Oh, thank you very much ^^
It works fine now.

Regaards ^.^

**Comment by themattharris** [comment]
Great, thanks for letting me know.
