### ISSUE TITLE
Twitter API 1.1 with thmOauth 0.7.5  not wortking anymore

### ISSUE THREAD

**Issue by ravindrasingh22** [themattharris/tmhOAuth#143]
I have developed a application in php to post the image with status in twitter.com with the help of tweet pic API. before that i API was working fine sudden last week i was posting the same and got status fail to post in twitter. after that  i have checked the response and update the library and API url in my application as API v. 1.1 . but it is not posting the image in tweetpic.

So can you help me the getting out from this issue.

**Comment by AgLiAn** [comment]
Fast fix, replace the:

"1/account/..." with "1.1/account/..."
"1/statuses/..." widh "1.1/statuses/..."

**Comment by ravindrasingh22** [comment]
It is done already only tweet pic is not posting.

**Comment by themattharris** [comment]
make sure the url is: https://api.twitter.com/1.1/statuses/update_with_media.json. Twitter moved the endpoint from upload.twitter.com when v1 was deprecated.

**Comment by ravindrasingh22** [comment]
I understood. now I am unable to post image V1.1 I am using tweetpic for post the image.

**Comment by themattharris** [comment]
can you share the code you are using so we can help. remember to remove any consumer and user secrets before pasting.

**Comment by ravindrasingh22** [comment]
Yes, I have contributed the module based on thmOauth API. Please go through the URL https://drupal.org/project/tweet_poster to download the code.

**Comment by themattharris** [comment]
ohhh you're using the 3rd party twitpic API, as opposed to twitter's own. looking at Twitpic's documentation (http://dev.twitpic.com/docs/2/upload/) it doesn't appear that they have migrated to v1.1 of the Twitter API for OAuth Echo. i suggest contacting Twitpic for support with OAuth Echo on their upload endpoint.

i also noticed a few other things when looking at your code:
- you're using two OAuth libraries at the same time (twitteroauth and tmhOAuth) - you only need one. i can't comment about twitteroauth's abilities, but i can say that tmhOAuth can do all the things you are using twitteroauth for.
- you're x_auth_service_provider value points to the v1 Twitter API url ('https://api.twitter.com/1/account/verify_credentials.json') which has been deprecated by twitter so will not work. this is the part you want to talk to Twitpic about
- further down the code you are making a request to $tmh_oauth->url('1/statuses/update') - this also won't work because it's using the deprecated v1 Twitter API. you should instead be using $tmh_oauth->url('1.1/statuses/update')
