### ISSUE TITLE
Error with tmhOAuth utilities file on Heroku

### ISSUE THREAD

**Issue by chrissimpkins** [themattharris/tmhOAuth#152]
Hi Matt,

I am using tmhOAuth in <a href="https://github.com/chrissimpkins/tweetledee/">Tweetledee</a> and a user (@kristoffernolgren) reported that when they attempt to load the files on Heroku they receive the following error on line 45 of the tmhUtilities.php file version 0.5.0.

`Fatal error: Call to undefined function mb_internal_encoding() in /app/www/tldlib/tmhUtilities.php on line 45`

<a href="https://github.com/chrissimpkins/tweetledee/blob/master/tweetledee/tldlib/tmhUtilities.php#L45">Here is a link to the line</a>.

It's unclear to me why the Heroku servers don't like this.  It is working fine elsewhere.  Any thoughts?  

Thanks much,
Chris

**Comment by themattharris** [comment]
hey chris,
tmhUtilities was removed from the project as it wasn't part of the core functionality.
that being said, the issue you are having is caused by the mbstring library not being part of your PHP install.

more information on the function can be found here: http://php.net/manual/en/function.mb-internal-encoding.php
with information about the library and ways to install it here: http://php.net/manual/en/book.mbstring.php

for background tmhUtilities uses mb_internal_encoding to set the state of the internal encoding used by mb_substr called later in the function here: https://github.com/chrissimpkins/tweetledee/blob/master/tweetledee/tldlib/tmhUtilities.php#L96

multibyte is used because twitter supports extended character sets, and without multibyte support, you cannot correctly count the position of extended UTF-8 characters (like emoji).

the solution is to ensure mbstring is installed, and enabled, in your PHP installation. more information on that is available here: http://www.php.net/manual/en/mbstring.installation.php

**Comment by chrissimpkins** [comment]
Thanks much for your response @themattharris.  The Heroku servers must not have this non-default extension for PHP installed. Really appreciate it.

-Chris

**Comment by lrytz** [comment]
to make it work on heroku (https://devcenter.heroku.com/articles/php-support)

``` diff
diff --git a/composer.json b/composer.json
index ee1c8a8..4db7c5c 100644
--- a/composer.json
+++ b/composer.json
@@ -14,6 +14,7 @@
         }
     ],
     "require": {
-        "php": ">=5.3.0"
+        "php": ">=5.3.0",
+        "ext-mbstring": "*"
     }
 }
```
