### ISSUE TITLE
twitpic by oauth_echo.php

### ISSUE THREAD

**Issue by tmizu23** [themattharris/tmhOAuth#16]
I tried to post a image to twitpic by oauth_echo.php. but it returned the error.
After I changed this code from "true" to "false" and "false" to "true", I could it. 
I don't know that this is the bug or not. so please give advise to me. 

function generate_verify_header($tmhOAuth) {
  // generate the verify crendentials header -- BUT DON'T SEND
  // note the https URL change - this is due to posterous requiring https in the X-Auth-Service-Provider
  $tmhOAuth->config['prevent_request'] = true; --> false
  $tmhOAuth->request('GET', $tmhOAuth->url('1/account/verify_credentials'));
  $tmhOAuth->config['prevent_request'] = false; -->true
}

**Comment by themattharris** [comment]
Can you add var_dump($tmhOAuth->response); to the end of your script to see which URL was queried and what the error response was?

**Comment by vivor** [comment]
I'm also trying to query twitpic with the method you used in oauth_echo.php but I can't get it to work either.

The following example doesn't seem to trigger the second request() (line 10), since $tmhOAuth->response is still filled from the first one (line 3).

```
function collect_twitpic(){
    $this->tmhOAuth->config['prevent_request'] = true;
    $this->tmhOAuth->request('GET', $this->tmhOAuth->url('1/account/verify_credentials'));
    $this->tmhOAuth->config['prevent_request'] = false;
    $this->tmhOAuth->headers = array(
        'X-Auth-Service-Provider' => $this->tmhOAuth->url('1/account/verify_credentials'),
        'X-Verify-Credentials-Authorization' => $this->tmhOAuth->auth_header
    );
    $url = 'http://api.twitpic.com/2/events/show.json';
    $this->tmhOAuth->request('POST', $url, array(), false, true);
    tmhutilities::pr($this->tmhOAuth->response);
}
```

When I comment out the config['prevent_request'] true/false lines it does actually send the request but twitpic's response is:

[response] => {"errors":[{"code":401,"message":"API key required for authentication."}]}

Any ideas?

**Comment by themattharris** [comment]
So I found an issue with my 'prevent_request' configuration which is fixed in the latest version of tmhOAuth.
I've also added a twitpic OAuth example [oauth_echo_twitpic.php].

When creating that example I hit the issue you have displayed above. It turns out twitpic has it's own API keys and you need to register for one to use their API (remember Twitpic is a third party service). I've included a link to the twitpic developer site at the top of the oauth_echo_twitpic.php - once there register an app and receive the key.

Hope that works for you. I'll close the issue but feel free to comment and reopen if you still have issues with this.

Best
@themattharris
