### ISSUE TITLE
Example with user auth

### ISSUE THREAD

**Issue by darkoromanov** [themattharris/tmhOAuth#27]
Hi, thanks for the great library first of all. 

I need to implement tmhOAuth but I need user oauth_token/secret because the tweet has to belong to the user but I don't know where to put the hands :) Could you show an example? Thanks in advance.

**Comment by themattharris** [comment]
Hey darkoromanov, 

The examples/oauth_flow.php demonstrates how to go take a user through the OAuth flow so that they authorize your application to Tweet on their behalf.

There is also documentation on https://dev.twitter.com/docs/auth/using-oauth which explains more about the process. You may also find https://dev.twitter.com/docs/auth/obtaining-access-tokens useful.

If you only need users to be able to Tweet from your application or website, you could use the Tweet Web Intent instead: https://twitter.com/about/resources/buttons

Hope that helps.

**Comment by themattharris** [comment]
Closing this one as there hasn't been any follow up to my response. Feel free to comment if you have any follow up though.
