### ISSUE TITLE
Getting User Info & Limit

### ISSUE THREAD

**Issue by Scottjutsu** [themattharris/tmhOAuth#33]
Hi Matt,

Thanks for the library - well done!  So far it's been pretty smooth sailing - I can successfully, for example, authenticate and get the user's favorite tweets.  But I'm stuck on a couple of points:

1) When I try to get the request limit I get the ip limit instead of the user limit.  I'm using the following code (with a real username, but I also tried it without the username b/c the docs say you don't have to pass it - same result either way - I get the ip limit:

``` php
$tmhOAuth = new tmhOAuth(array(
    'consumer_key'    => $c_key,
    'consumer_secret' => $c_secret,
    'user_token'      => $token,
    'user_secret'     => $secret,
));

$url = "https://api.twitter.com/1/account/rate_limit_status/[USERNAME].json";

$tmhOAuth->request("GET", $url);

if ($tmhOAuth->response['code'] == 200) {
  $data = json_decode($tmhOAuth->response['response'], true);
} else {
  $data = htmlentities($tmhOAuth->response['response']);
  echo 'There was an error.' . PHP_EOL;
}
var_dump($data);
```

I can tell it's the ip limit because the max int in the response is 150.  What am I missing here?

2) What is the proper/best way to get the current authenticated user's basic info (username, id, etc) using the library?  When I make a request to:

https://api.twitter.com/1/account/verify_credentials.json 

OR 

https://api.twitter.com/1/account/verify_credentials/[USERNAME].json

... using the same code that I've been using for favorites and request limit, I get "Could not authenticate with OAuth".  And when I replace $url with $tmhOAuth->url('1/account/verify_credentials') I get an "expired token" error, which doesn't make sense to me because I can use the same token to get a list of favorite tweets 10 seconds later.

I hope I'm not missing something really simple, but it's entirely possible - my brain is so fried.

**Comment by themattharris** [comment]
Hey cypherD,

For question 1, make sure the token and secret are valid for the user you are making requests on behalf. For testing you can find out your own on dev.twitter.com/apps - and yeah the 150 limit means it considers you unauthenticated.

For question 2, the correct endpoint is https://api.twitter.com/1/account/verify_credentials.json (without the username) (doc: https://dev.twitter.com/docs/api/1/get/account/verify_credentials).

As you are getting the error "Could not authenticate with OAuth" and also "expired token" i'm pretty certain the issue is either incorrect or temporary tokens are being passed in your requests. The best thing to do here is copy your own token/secret from dev.twitter.com/apps and see if that works. If it does, you know something is wrong in the way you obtain or store the user tokens in the the live app.

Some of the API endpoints on the Twitter API will default to unauthenticated if the credentials you are sending are invalid. If this happens there will be a header `X-Warning` added to the response which you can inspect by doing `var_dump($tmhOAuth->response['headers']);`. If the credentials were bad the header will read:

`x_warning: Invalid OAuth credentials detected`

I think this is why the token is allowing you to access the 10 favorite tweets (unauthenticated) but doesn't allow you to access protected 'authenticated only' resources.

Let me know how you get along with the token/secret from dev.twitter.com/apps

**Comment by Scottjutsu** [comment]
Spot on.  It seems I tripped up somewhere among all of the steps of the 'OAuth dance', as you aptly put it.  Thanks so much!

**Comment by themattharris** [comment]
Great, glad you got it working!
