### ISSUE TITLE
Urgent !!! Issues with photo_tweet.php

### ISSUE THREAD

**Issue by cromanelli** [themattharris/tmhOAuth#34]
Hello, 

When i try to upload a photo using photo_tweet.php i get no response from twitter and 

 $code = 0 

after requesting a var_dump($code) . 

It does not even tells me what the error is . 

Please this is an urgent issue can you please help me ?

**Comment by themattharris** [comment]
Hi cromanelli,

I'm happy to help and respond to issues raised with the library when I can. Marking things as urgent is unfriendly though so please don't do that.

A response code of 0 means curl could not make the request to the remote server. This is mostly likely due to a problem establishing the SSL connection to twitter.com.

To help diagnose what's going on you can inspect the $tmhOAuth->response object. In particular, there is a variable 'error' which will often contain more information on what is wrong. You can inspect this by adding the line below to the end of your script:
    var_dump($tmhOAuth->response['error']);

Hopefully that error message will help point you in the right direction.

Let me know how it goes.

**Comment by cromanelli** [comment]
Hi  themattharris

I am sorry for marking this issue as urgent my intention was never an unfriendly one. But when i wrote this down i was at a venue 2 hours before a live event and I kept getting that and of course not tweeting anything. Not that i did not make my homework and try the app before using it but that morning the thing decided not to work any more, I guess my friend Murphy wanted to take a role part in the development. 

I must say that the app connected to internet over a 3G (EGDE more likely) mobile network and the pictures i wanted to upload where on the 80k range i had the idea that i could not connect and running the script you told me confirmed it.

SSL connection timeout

Looking at your library i saw a cURL Timeout parameter and a cURL connectimeout . I changed them to 300 Seconds so i should not have any problem

Thanks and kudos for developing such an great and easy to use library 

C

**Comment by themattharris** [comment]
Thanks, I understand the pressure of hackdays - i've been to many myself. I appreciate the followup.
I know you've closed the issue but for information you were correct that I added timeout parameters to allow easier configuration for these kind of situations.

So, in your script you can initialise the $tmhOAuth object with these configured (so you don't need to modify the basecode).

```
$tmhOAuth = new tmhOAuth(array(
  'consumer_key'        => 'YOUR_CONSUMER_KEY',
  'consumer_secret'     => 'YOUR_CONSUMER_SECRET',
  'user_token'          => 'A_USER_TOKEN',
  'user_secret'         => 'A_USER_SECRET',
  'curl_connecttimeout' => 30,
  'curl_timeout'        => 10,
));
```
