### ISSUE TITLE
Failed to validate OAuth signature and token

### ISSUE THREAD

**Issue by jaimerump** [themattharris/tmhOAuth#72]
I'm trying to use the library to get a Twitter user's access tokens via the code presented in the oauth_flow.php example. https://github.com/themattharris/tmhOAuth/blob/master/examples/oauth_flow.php

Every time I get the error "failed to validate oauth signature and token" from the very first request that is made in the request_token function. I have checked the server time and it is within about 5 seconds of twitter's servers. cacert.pem is in the right location where curl says it is looking for it. I have 'use_ssl' and 'curl_ssl_verifypeer' set to false since I don't currently have an ssl certificate set up. I haven't managed to find anything else that might cause this.

Here is my response object, and I have the rest of the tmhOAuth object dumped if you need it.

```
["response"]=> array(6) { 
    ["headers"]=> array(16) { 
        ["date"]=> string(29) "Sat, 25 Aug 2012 17:35:27 GMT" 
        ["status"]=> string(16) "401 Unauthorized" 
        ["x_runtime"]=> string(7) "0.02047" 
        ["x_frame_options"]=> string(10) "SAMEORIGIN" 
        ["x_transaction"]=> string(16) "93a2e5d04911a32a" 
        ["pragma"]=> string(8) "no-cache" 
        ["expires"]=> string(29) "Tue, 31 Mar 1981 05:00:00 GMT" 
        ["last_modified"]=> string(29) "Sat, 25 Aug 2012 17:35:27 GMT" 
        ["x_mid"]=> string(40) "5805700d244470965b51b732ac623cdbfd9c4275" 
        ["cache_control"]=> string(62) "no-cache, no-store, must-revalidate, pre-check=0, post-check=0" 
        ["content_type"]=> string(24) "text/html; charset=utf-8" 
        ["set_cookie"]=> string(265) "_twitter_sess=cookie; domain=.twitter.com; path=/; HttpOnly" 
        ["vary"]=> string(15) "Accept-Encoding" 
        ["content_encoding"]=> string(4) "gzip" [
        "content_length"]=> string(2) "62" 
        ["server"]=> string(3) "tfe" 
    } 
    ["code"]=> int(401) 
    ["response"]=> string(44) "Failed to validate oauth signature and token" 
    ["info"]=> array(23) { 
        ["url"]=> string(42) "http://api.twitter.com/oauth/request_token" 
        ["content_type"]=> string(24) "text/html; charset=utf-8" 
        ["http_code"]=> int(401) 
        ["header_size"]=> int(1030) 
        ["request_size"]=> int(498) 
        ["filetime"]=> int(-1) 
        ["ssl_verify_result"]=> int(0) 
        ["redirect_count"]=> int(0) 
        ["total_time"]=> float(0.314552) 
        ["namelookup_time"]=> float(0.123387) 
        ["connect_time"]=> float(0.200685) 
        ["pretransfer_time"]=> float(0.200689) 
        ["size_upload"]=> float(0) 
        ["size_download"]=> float(62) 
        ["speed_download"]=> float(197) 
        ["speed_upload"]=> float(0) 
        ["download_content_length"]=> float(62) 
        ["upload_content_length"]=> float(-1) 
        ["starttransfer_time"]=> float(0.314367) 
        ["redirect_time"]=> float(0) 
        ["certinfo"]=> array(0) { } 
        ["redirect_url"]=> string(0) "" 
        ["request_header"]=> string(498) "POST /oauth/request_token HTTP/1.1 User-Agent: tmhOAuth 0.621-SSL - //github.com/themattharris/tmhOAuth Host: api.twitter.com Accept: */* Accept-Encoding: deflate, gzip Authorization: OAuth oauth_callback="http%3A%2F%2Fcompleteset.us%2Fsettings%2Ftwitterlink", oauth_consumer_key="key", oauth_nonce="nonce", oauth_signature="sig", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345916127", oauth_version="1.0" " 
    } 
    ["error"]=> string(0) "" 
    ["errno"]=> int(0) } }
```

**Comment by themattharris** [comment]
hey jaimerump,

thanks for the details write up of the issue you are experiencing.
the error response you are getting is coming directly from the Twitter API, which means there isn't an issue with the timeout or SSL configuration - although it's great you checked. it is recommended you use SSL though (so turned that back on is a good idea).

this error usually means there is an issue with the signature that was created. without knowing exactly what your configuration values are it's difficult to identify where the issue lies.

here's what i would do:
- make sure tmhOAuth.php and oauth_flow.php are unchanged from the versions in the repository on github (just in case something changed inadvertently)
- copy the consumer key and consumer secret for your application from dev.twitter.com again
- run the script again in a browser.

let me know how it goes. if you continue to have issues let me know the exact details directly (rather than through this open issue ticket).

**Comment by themattharris** [comment]
closing this one out as it's been a while without a response. if this is still an issue add a comment and i'll look into it.
