### ISSUE TITLE
how to get permanent user token and secret

### ISSUE THREAD

**Issue by anchetaWern** [themattharris/tmhOAuth#84]
I'm always getting the 401 error whenever I make use of the user token and user secret:
I'm looking on the code at: https://github.com/themattharris/tmhOAuth-examples/blob/master/oauth_flow.php
so I basically have this on the access_token() function. So I'm assuming that the user has already been verified at that point in time.

```
function access_token($tmhOAuth) {
  $tmhOAuth->config['user_token']  = $_SESSION['oauth']['oauth_token'];
  $tmhOAuth->config['user_secret'] = $_SESSION['oauth']['oauth_token_secret'];

  //store user token and secret to a session to be accessed on a different page
  $_SESSION['u_token'] =  $tmhOAuth->config['user_token'];
  $_SESSION['u_secret'] = $tmhOAuth->config['user_secret'];  

  $code = $tmhOAuth->request(
    'POST',
    $tmhOAuth->url('oauth/access_token', ''),
    array(
      'oauth_verifier' => $_REQUEST['oauth_verifier']
    )
  );

  if ($code == 200) {
    $_SESSION['access_token'] = $tmhOAuth->extract_params($tmhOAuth->response['response']);
    unset($_SESSION['oauth']);
    header('Location: ' . tmhUtilities::php_self());
  } else {
    outputError($tmhOAuth);
  }
}
```

I make use of those in another page as follows:

```
<?php
session_start();
require_once('tmhoauth/tmhOAuth.php');
require_once('tmhoauth/tmhUtilities.php');

$tmhOAuth = new tmhOAuth(array(
  'consumer_key'    => 'xxx',
  'consumer_secret' => 'xxx',
  $_SESSION['u_token'],
 $_SESSION['u_secret']
));

$tweet = 'tweet';

$code = $tmhOAuth->request('POST', $tmhOAuth->url('1/statuses/update'), array(
  'status' => $tweet
));

echo json_encode($code); //I always get 401 here
?>
```

My question is where do I get the permanent user token and user secret? It seems like the one that I'm using is changing everytime  a request is made so it doesn't recognize it as the token of the user. Thanks in advance!

**Comment by themattharris** [comment]
the oauth_flow example uses sessions to store the token and secret. if you want to retain them you'll need to add a function which stores (securely) the token and secret in a database of users for your system.

that way, when the session ends, the user token and secret can be read from the database instead of the now empty session.

the other thing is the permanent token and secret are returned by the /oauth/access_token request. in your code you are storing those values into this variable:

```
$_SESSION['access_token']
```

but then on the next page you continue to read from:

```
$_SESSION['u_token']
$_SESSION['u_secret']
```

what this means is you are reading the permanent token but using the temporary one from the previous request.
hope that helps - let me know how it goes.

**Comment by themattharris** [comment]
closing this one out as it's been a while without any follow up questions
