### ISSUE TITLE
£ sign not working in tweets

### ISSUE THREAD

**Issue by stuayre** [themattharris/tmhOAuth#86]
posting tweets are working fine, until I put one that uses the £ sign, then I get an error: 400

it works for for $ signs tho, just won't work for £

is this a limitation?

**Comment by neave** [comment]
I've just checked this and can confirm that using a £ as the first character in a tweet (posted with an image) will fail (using either the v1.0 or v1.1 API). Putting the £ character anywhere else in the tweet works. This is identical to issue #46 where an @ character at the start of a tweet will fail also.

The fix is to check the first character of the tweet when posting and to prefix it with a space. Twitter then trims the space away and the tweet is published.

Perhaps there should be more checks to see what other characters do not work when used as the first character in a tweet?

**Comment by stuayre** [comment]
Hmm thanks for the reply, I was putting the £ sign in the middle of the tweet tho. it also doesn't seem to like ( ) am I doing something wrong?

**Comment by neave** [comment]
Hm OK I'm not seeing the £ problem any more after a few more checks. Not sure what's going on here! Tried a few other characters too ! % ^ & \* + ) and ( and they all seem to be OK.

**Comment by stuayre** [comment]
Yeah weird, I made a new script and it seems to work, but in my application this is what im getting back...

{"error":"Invalid Unicode value in one or more parameters","request":"\/1\/statuses\/update.json"}"
    ["headers"]=>
    array(14) {
      ["date"]=>
      string(29) "Wed, 03 Oct 2012 14:14:33 GMT"
      ["status"]=>
      string(15) "400 Bad Request"

["request_params"]=>
  string(48) "status=this%20is%20a%20%A3%20sign%20test%20again"

it works with other strings tho :/

**Comment by stuayre** [comment]
I got it working, I had two scripts exactly the same... one worked one didn't i dont know why. so i copied everything over from my application into the working script apart from the function to post to twitter and its working now. thanks!

**Comment by themattharris** [comment]
just getting a chance to look at this. first off, i'm pleased you got your script working.

@stuayre: looking at the example you posted two comments above shows there is a problem with the encoded parameters - but it's unclear why. when URI encoded a £ is %C2%A3 not %A3. are you posting from a text box on a web page? or maybe using a texteditor which changed the character set of the script from UTF-8? 

for reference here's what i did - which returned a 200 OK response.

```
$code = $tmhOAuth->request('POST', $tmhOAuth->url('1.1/statuses/update'), array(
  'status' => '£ show me the £££'
));
```

which created the following request parameters:

```
status=%C2%A3%20show%20me%20the%20%C2%A3%C2%A3%C2%A3
```

because £ is a special symbol you need to make sure the editor you are using doesn't save your script in a different character set - as that will cause problems.

i'll close this one out as i think you resolved the issue, and my explanation provides some background for anyone else who may come across this issue.
